export const products = [   
    {
        id: 1,
        name: "Legion Lenovo",
        description: "A powerful gaming laptop with high-end specs for immersive gaming experiences.",
        image: "https://i.ebayimg.com/images/g/SzIAAOSwA9tj6s6x/s-l1600.jpg",
        price:999.99 + "€" ,
    },
    {
        id: 2,
        name: "iPhone 14 - 128GB",
        description: "The latest iPhone model with 128GB storage for all your multimedia needs.",
        image: "https://imagineonline.store/cdn/shop/files/r1595_Yellow_PDP_Image_Position-1A__en-IN_3b89cb18-d778-42d6-b944-6fbb4c3fb47f_823x.jpg?v=1692352177",
        price:499.99 + "€" ,
    },
    {
        id: 3,
        name: "ANC Wireless Headphones",
        description: "Noise-canceling wireless headphones for an immersive audio experience.",
        image: "https://d3lnc7yu1ksdj.cloudfront.net/wp-content/uploads/2022/08/Hesh-ANC_True-Black_S6HHW-N740_Hero_v001.jpg",
        price:79.99 + "€" ,
    },
    {
        id: 4,
        name: "Gaming PC",
        description: "A high-performance gaming PC for playing the latest games with ease.",
        image: "https://www.awd-it.co.uk/media/catalog/product/x/_/x_air_mesh_arc_pc_2.jpg",
        price:1199.99 + "€" ,
    },
    {
        id: 5,
        name: "Samsung Galaxy Tab",
        description: "A feature-packed tablet for work, entertainment, and productivity on the go.",
        image: "https://static.independent.co.uk/2022/04/07/14/samsung%20galaxy%20tab%20s8.jpg",
        price:299.99+ "€" ,
    },
    {
        id: 6,
        name: "Smartwatch",
        description: "A stylish smartwatch that tracks your fitness and keeps you connected on the move.",
        image: "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1666633876-31xSAHViI8L._SL500_.jpg?crop=1xw:1.00xh;center,top&resize=980:*",
        price:149.99+ "€" ,
    },
    {
        id: 7,
        name: "Power bank",
        description: "A portable power bank to keep your devices charged while on the go.",
        image: "https://m.media-amazon.com/images/I/612vaudnEkL.jpg",
        price:29.99+ "€" ,
    },
    {
        id: 8,
        name: "JBL Flip 5 Bluetooth Speaker",
        description: "A portable Bluetooth speaker with high-quality sound for your music and podcasts.",
        image: "https://www.seanhennessy.ie/image/thumbnails/1d/22/JBLFLIP5BLU_jpg-119337-800x800.jpg",
        price:49.99+ "€" ,
    },
    {
        id: 9,
        name: "WD 4TB USB 3.0",
        description: "A high-capacity external hard drive for all your storage needs.",
        image: "https://snpi.dell.com/snp/images/products/large/en-us~AA888500/AA888500.jpg",
        price:89.99+ "€" ,
    },
    {
        id: 10,
        name: "Meta Quest 2 - Advanced All-In-One",
        description: "A virtual reality headset for gaming and immersive experiences.",
        image: "https://media.gamestop.com/i/gamestop/11107421-11107422_ALT01?$pdp$",
        price:199.99+ "€" ,
    },
    {
        id: 11,
        name: "Wireless Keyboard",
        description: "A wireless keyboard for comfortable typing and productivity.",
        image: "https://dorangadget.com/wp-content/uploads/2021/11/keyboard-laptop-keyboard-komputer-keyboard-adalah-harga-keyboard-murah-1-2.jpg",
        price:49.99+ "€" ,
    },
    {
        id: 12,
        name: "In-Ear Earbuds",
        description: "High-quality in-ear earbuds for enjoying music and audio on the go.",
        image: "https://www.mytrendyphone.ie/images/Samsung-Galaxy-Buds-Live-SM-R180NZKAEUE-Mystic-Black-8806090486869-20082020-1-p.webp",
        price:29.99+ "€" ,
    },
    {
        id: 13,
        name: "4K Ultra HD TV",
        description: "A 4K Ultra HD TV for stunning visuals and an immersive viewing experience.",
        image: "https://i0.wp.com/interplast-group.com/wp-content/uploads/2023/09/UE85CU7172.jpg?fit=1000%2C1000&ssl=1",
        price:799.99+ "€" ,
    },
    {
        id: 14,
        name: "Sony ZV-1 Digital Camera (White)",
        description: "A high-quality digital camera for capturing memorable moments in style.",
        image: "https://digitalshopbd.com/public/uploads/all/zu0SfccpNrsj3ln9g4EcrggSsHLRAMrRMNKlrQaR.jpg",
        price:399.99+ "€" ,
    },
    {
        id: 15,
        name: "PS5 Gaming Console",
        description: "The next-gen gaming console for an immersive gaming experience.",
        image: "https://www.pbtech.co.nz/imgprod/G/A/GAMSNY5504__1.jpg",
        price:299.99+ "€" ,
    },
    {
        id: 16,
        name: "Laptop Backpack",
        description: "A durable and stylish backpack designed to carry your laptop and essentials.",
        image: "https://www.rivacase.com/images/virtuemart/product/8365_blue.4260403573181.ver01.jpg",
        price:39.99+ "€" ,
    },
    {
        id: 17,
        name: "Portable Monitor",
        description: "A portable monitor for on-the-go productivity and entertainment.",
        image: "https://m.media-amazon.com/images/I/717-i0yqNzL._AC_UF894,1000_QL80_.jpg",
        price:199.99+ "€" ,
    },
    {
        id: 18,
        name: "Alexa Smart Hub",
        description: "An AI-powered smart hub for controlling your smart home devices.",
        image: "https://adminapi.applegadgetsbd.com/storage/media/large/2563-67586.jpg",
        price:149.99+ "€" ,
    },
    {
        id: 19,
        name: "Black Graphic Tablet, For Laptop",
        description: "A graphic tablet for digital artists and designers to create stunning artwork.",
        image: "https://www.acegizmo.com/wp-content/uploads/2022/05/1105G430.jpg",
        price:149.99+ "€" ,
    },
    {
        id: 20,
        name: "Samsung 34-Inch Ultrawide Monitor",
        description: "A high-resolution ultrawide monitor for multitasking and gaming.",
        image: "https://images.samsung.com/is/image/samsung/ae-curved-cf390-lc34f390fwmxue-lperspectiveblack-126263281?$720_576_PNG$",
        price:499.99+ "€" ,
    },
    {
        id: 21,
        name: "Smart Refrigerator",
        description: "A state-of-the-art smart refrigerator with advanced features and ample storage space for your groceries.",
        image: "https://images.thdstatic.com/productImages/a894ea42-1f5b-4b95-9bf1-c303e3be330b/svn/fingerprint-resistant-stainless-steel-samsung-french-door-refrigerators-rf27t5501sr-64_1000.jpg",
        price:1099.99+ "€" ,
    },
    {
        id: 22,
        name: "Robot Vacuum Cleaner",
        description: "A robot vacuum cleaner that keeps your floors clean and tidy with minimal effort.",
        image: "https://m.media-amazon.com/images/I/61eRk8uocmS.jpg",
        price:249.99+ "€" ,
    },
    {
        id: 23,
        name: "Wireless Router",
        description: "A high-performance wireless router for fast and reliable internet connectivity in your home or office.",
        image: "https://www.linksys.com/on/demandware.static/-/Sites-master-product-catalog/default/dw704bc017/images/hi-res/4/89485812_E5350_left_quarter.jpg",
        price:79.99+ "€" ,
    },
    {
        id: 24,
        name: "Smart Thermostat",
        description: "A smart thermostat that helps you control and optimize your home's heating and cooling systems for energy efficiency.",
        image: "https://m.media-amazon.com/images/I/51YWnoWYbkL.jpg",
        price:129.99+ "€" ,
    },
    {
        id: 25,
        name: "External SSD Drive",
        description: "A high-speed external SSD drive for lightning-fast data transfer and storage capabilities.",
        image: "https://www.ravpower.com/cdn/shop/products/um003.jpg?v=1625749285",
        price:69.99+ "€" ,
    },
    {
        id: 26,
        name: "Microsoft Bluetooth Mouse (Mint) - JB Hi-Fi",
        description: "A stylish and reliable Microsoft Bluetooth mouse for smooth and precise cursor control.",
        image: "https://www.jbhifi.com.au/cdn/shop/products/414439-Product-0-I-637177087606327923_grande.jpg",
        price:19.99+ "€" ,
    },
    {
        id: 27,
        name: "Video Doorbell Pro",
        description: "A high-quality video doorbell for enhancing the security of your home with real-time monitoring and communication.",
        image: "https://cdn.shopify.com/s/files/1/2393/8647/products/ring_video_doorbell_wired_pro_1500x1500_2x_60698235-40cb-4924-a4f8-f84b7cf0ec6a.jpg?v=1678279636",
        price:129.99+ "€" ,
    },
    {
        id: 28,
        name: "Wireless Charging Pad",
        description: "A wireless charging pad for conveniently charging your compatible devices without the need for cables.",
        image: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HPU72?wid=8000&hei=5558&fmt=jpeg&qlt=95&.v=1636763768000",
        price:29.99+ "€" ,
    },
    {
        id: 29,
        name: "SSD SATA 500GB",
        description: "A high-capacity SSD SATA drive for improved storage performance and faster data access.",
        image: "https://m.media-amazon.com/images/I/61I4dVw+HEL.jpg",
        price:119.99+ "€" ,
    },
    {
        id: 30,
        name: "Nintendo Switch (OLED Model) The Legend of Zelda",
        description: "The Nintendo Switch (OLED Model) featuring The Legend of Zelda game for an enhanced gaming experience.",
        image: "https://c1-ebgames.eb-cdn.com.au/merchandising/images/packshots/f654997654674d5996bc54cc2c627c6d_Original.jpg",
        price:549.99+ "€" ,
    },
    {
        id: 31,
        name: "4K Ultra HD Blu-ray Player BDP7501/F7 | Philips",
        description: "A 4K Ultra HD Blu-ray player for enjoying your favorite movies and TV shows in stunning detail and clarity.",
        image: "https://images.philips.com/is/image/PhilipsConsumer/BDP7501_F7-IMS-en_CA?$jpglarge$&wid=1250",
        price:149.99+ "€" ,
    },
    {
        id: 32,
        name: "Xiaomi Wi-Fi Range Extender",
        description: "A Wi-Fi range extender that expands your network coverage for improved connectivity throughout your home or office.",
        image: "https://www.tradeinn.com/f/13758/137584646_2/xiaomi-mi-wifi-range-extender-pro-wifi-repeater.jpg",
        price:39.99+ "€" ,
    },
    {
        id: 33,
        name: "Smartwatch Charger",
        description: "A charger designed for your smartwatch, ensuring it's always ready to go when you are.",
        image: "https://m.media-amazon.com/images/I/51Xba2mO7vL.jpg",
        price:14.99+ "€" ,
    },
    {
        id: 34,
        name: "WHITE SHARK gaming mechanical keyboard",
        description: "A gaming mechanical keyboard with high precision and customizable features for a competitive edge in gaming.",
        image: "https://hyperlift.hr/storage/app/uploads/public/619/73c/02d/61973c02d3339067588327.jpg",
        price:69.99+ "€" ,
    },
    {
        id: 35,
        name: "Wireless Desk Lamp",
        description: "A wireless desk lamp with LED lighting for versatile and convenient illumination in any workspace.",
        image: "https://tghsmart.ie/wp-content/uploads/2020/11/WIRELESS-CHARGING-LAMPS-LED-LIGHTING-1-black.jpg",
        price:34.99+ "€" ,
    },
    {
        id: 36,
        name: "Cloud || - Gaming Headset | Hyper X",
        description: "A gaming headset designed for immersive audio experiences and clear communication during gaming sessions.",
        image: "https://hyperx.com/cdn/shop/files/hyperx_cloud_ii_red_2_main_mixer_2048x2048.jpg?v=1695397316",
        price:119.99+ "€" ,
    },         
    {
    id: 37,
    name: "DJI Mavic Air 2 Drone",
    description: "A high-quality drone with 4K camera and intelligent flight features for capturing stunning aerial photos and videos.",
    image: "https://www.dji.com/skin/frontend/phoenix/default/images/catalog/product-page-hero__thumbnail/DJI_Mavic_Air_2_08.jpg",
    price: 799.99 + "€",
},
{
    id: 38,
    name: "Bose QuietComfort 45 Headphones",
    description: "Premium noise-canceling headphones for the ultimate audio experience and comfortable wear.",
    image: "https://cdn-ak.f.st-hatena.com/images/fotolife/Y/YAMPAi/20210827/20210827170023.jpg",
    price: 349.99 + "€",
},
{
    id: 39,
    name: "Canon EOS 5D Mark IV DSLR Camera",
    description: "A professional-grade DSLR camera for high-resolution photography and 4K video recording.",
    image: "https://images.unsplash.com/photo-1532635245-5a1a01655f02",
    price: 2499.99 + "€",
},
{
    id: 40,
    name: "Apple Watch Series 7",
    description: "The latest Apple Watch with a larger display, health tracking features, and more.",
    image: "https://m.media-amazon.com/images/I/81GKDqxjL3L._AC_SL1500_.jpg",
    price: 349.99 + "€",
},
{
    id: 41,
    name: "LG OLED 4K Smart TV",
    description: "An OLED TV with stunning picture quality, smart features, and immersive sound.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71CWpNR4HHL._AC_SX466_.jpg",
    price: 1499.99 + "€",
},
{
    id: 42,
    name: "Kindle Paperwhite eReader",
    description: "A waterproof eReader for enjoying your favorite books on the go with a high-resolution display.",
    image: "https://m.media-amazon.com/images/I/61geO8fdxlL._SL1000_.jpg",
    price: 129.99 + "€",
},
{
    id: 43,
    name: "Samsung 27-Inch Curved Gaming Monitor",
    description: "A curved gaming monitor with fast refresh rates and vibrant colors for an immersive gaming experience.",
    image: "https://images.samsung.com/is/image/samsung/uk-curved-gaming-cf396-lc27f396fhuxen-136152258?$PD_GALLERY_L_JPG$",
    price: 299.99 + "€",
},
{
    id: 44,
    name: "Fujifilm Instax Mini 11 Instant Camera",
    description: "An instant camera for capturing and printing memorable photos in seconds.",
    image: "https://m.media-amazon.com/images/I/81GGPR+3X5L._AC_SX425_.jpg",
    price: 69.99 + "€",
},
{
    id: 45,
    name: "Samsung Galaxy S22",
    description: "The latest Samsung Galaxy smartphone with advanced camera features and powerful performance.",
    image: "https://www.samsung.com/de/smartphones/galaxy-s22-5g/SM-S901FZKJDBT/gallery/05-2560x1440.jpg",
    price: 799.99 + "€",
},
{
    id: 46,
    name: "Logitech G Pro X Mechanical Gaming Keyboard",
    description: "A mechanical gaming keyboard with customizable switches and RGB lighting for competitive gaming.",
    image: "https://image-us.s1.cdn.gpnl.eu/r8Fn1JSRLY7AzUQh_-Rrr_2BbClB_Y-XW8PnXkQyZrvrUNoYH0j91eGC7wrk3UWpC5qeh9eWUPK_Gc8YllUz0Fv59pZtdGshXrrqozEG-EbBQgUjH1k32k8I5S74bqynqwY",
    price: 129.99 + "€",
},
{
    id: 47,
    name: "Google Nest Hub Max",
    description: "A smart display with Google Assistant for controlling your smart home and staying connected.",
    image: "https://cdn.vox-cdn.com/thumbor/ozp1XCLgJKWtrP1R0JF9K-A2r_I=/0x0:2040x1360/1820x1213/filters:focal(857x517:1183x843):format(webp)/cdn.vox-cdn.com/uploads/chorus_image/image/65393236/akrales_190917_3666_0090.0.jpg",
    price: 229.99 + "€",
},
{
    id: 48,
    name: "Nikon D850 DSLR Camera",
    description: "A high-resolution DSLR camera with exceptional image quality and professional features.",
    image: "https://www.nikon.co.uk/media/productImages/digital-cameras/full-frame/d850/vbpyjr0vznkq0liyejmw_d850_front.png",
    price: 2999.99 + "€",
},
{
    id: 49,
    name: "Bose SoundLink Revolve+ Bluetooth Speaker",
    description: "A portable Bluetooth speaker with 360-degree sound and long-lasting battery life.",
    image: "https://m.media-amazon.com/images/I/61nY5lLhllL._AC_SX425_.jpg",
    price: 199.99 + "€",
},
{
    id: 50,
    name: "Nintendo Switch Pro Controller",
    description: "A high-quality controller for the Nintendo Switch, designed for a comfortable gaming experience.",
    image: "https://images-na.ssl-images-amazon.com/images/I/61JmKU6w9nL._SL1200_.jpg",
    price: 69.99 + "€",
},
{
    id: 51,
    name: "Dell Ultrasharp 27-inch Monitor",
    description: "A high-quality 27-inch monitor for professional work and stunning visual clarity.",
    image: "https://i.dell.com/is/image/DellContent//content/dam/global-site-design/product_images/peripherals/mas_assets/aw2521hfl/visuals/masaw2521hfl_vis0001_qhd_001.jpg?fmt=webp",
    price: 449.99 + "€",
},
{
    id: 52,
    name: "Sony WH-1000XM4 Wireless Headphones",
    description: "Premium wireless headphones with noise-canceling technology and exceptional audio quality.",
    image: "https://images.sony.com/is/image/Sony/wh-1000xm4-gallery-1-us-0610?$PNGAlpha$&wid=775&hei=775",
    price: 299.99 + "€",
},
{
    id: 53,
    name: "MacBook Pro 16-inch",
    description: "A powerful 16-inch MacBook Pro with a stunning Retina display and high-end performance.",
    image: "https://www.apple.com/v/mac/home/ab/images/overview/design/macbook_pro__dfrd7y24jjka_large.jpg",
    price: 2399.99 + "€",
},
{
    id: 54,
    name: "GoPro HERO10 Black",
    description: "The latest GoPro action camera with 5.3K video recording and advanced stabilization.",
    image: "https://images-na.ssl-images-amazon.com/images/I/81X62uF77QL._AC_SL1500_.jpg",
    price: 499.99 + "€",
},
{
    id: 55,
    name: "Bose Home Speaker 500",
    description: "A smart home speaker with voice control and room-filling sound.",
    image: "https://images-na.ssl-images-amazon.com/images/I/41VwIezXy3L._AC_.jpg",
    price: 349.99 + "€",
},
{
    id: 56,
    name: "DJI Mini 2 Drone",
    description: "An ultra-compact drone with 4K camera and enhanced flight features for aerial photography.",
    image: "https://m.media-amazon.com/images/I/81OPWU9TukL._AC_SL1500_.jpg",
    price: 449.99 + "€",
},
{
    id: 57,
    name: "Samsung Odyssey G7 Gaming Monitor",
    description: "A curved gaming monitor with QLED technology and rapid refresh rates for gaming enthusiasts.",
    image: "https://images.samsung.com/is/image/samsung/uk-odyssey-gaming-g7-c32g7tqswu-lc32g7tqswuxen-394329599?$PD_GALLERY_L_JPG$",
    price: 799.99 + "€",
},
{
    id: 58,
    name: "Canon EOS R6 Mirrorless Camera",
    description: "A mirrorless camera with 4K video capabilities and advanced autofocus for photography and videography.",
    image: "https://www.canon.com.cy/images/imagePreviews/A30874992.jpg",
    price: 2499.99 + "€",
},
{
    id: 59,
    name: "Apple iPad Air (4th Generation)",
    description: "A sleek and powerful iPad with a liquid retina display and performance to match.",
    image: "https://www.apple.com/newsroom/images/product/ipad/standard/Apple_iPad_Air_5th_gen_2022_Geometry_tilted_back_NS-20220308_191502_standard.jpg.large.jpg",
    price: 599.99 + "€",
},
{
    id: 60,
    name: "Sony PlayStation 5",
    description: "The next-gen gaming console for immersive gaming experiences and stunning graphics.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71lxaWEy21L._SL1500_.jpg",
    price: 499.99 + "€",
},
{
    id: 61,
    name: "Samsung Galaxy Z Fold 3",
    description: "A foldable smartphone with a large display and versatile functionality.",
    image: "https://m.media-amazon.com/images/I/61wMMLwQj4L._SL1000_.jpg",
    price: 1799.99 + "€",
},
{
    id: 62,
    name: "Garmin Fenix 7 Multisport Watch",
    description: "A premium multisport watch with advanced fitness and navigation features.",
    image: "https://m.media-amazon.com/images/I/71ezjV2kXNL._SL1500_.jpg",
    price: 699.99 + "€",
},
{
    id: 63,
    name: "Dell XPS 13 Laptop",
    description: "An ultra-portable laptop with a stunning InfinityEdge display and powerful performance.",
    image: "https://i.dell.com/is/image/DellContent//content/dam/global-site-design/product_images/notebooks/xps_13_9300/spi/ng/notebooks-xps-13-9300-hero-504x350-ng.png?fmt=webp",
    price: 1299.99 + "€",
},
{
    id: 64,
    name: "Logitech G Pro Wireless Gaming Mouse",
    description: "A wireless gaming mouse with ultra-precise sensors and customizable buttons for competitive gaming.",
    image: "https://image-us.s1.cdn.gpnl.eu/0m3eOhWFeOJBezS4ahE1IszSgViGxZ6gkq97OqU0GrMZMzJBeXyI9OgPMZMJGiOYFmjOgoS0GzgDzgF9.jpg",
    price: 149.99 + "€",
},
{
    id: 65,
    name: "Fitbit Versa 3 Smartwatch",
    description: "A smartwatch with built-in GPS and health tracking features for an active lifestyle.",
    image: "https://www.fitbit.com/global/content/dam/fitbit/global/pdp/versa-3/pdp-v3-hero-blue_1x.png",
    price: 199.99 + "€",
},
{
    id: 66,
    name: "Anker PowerCore Portable Charger",
    description: "A high-capacity portable charger for keeping your devices powered on the go.",
    image: "https://d2211byn0pk9fi.cloudfront.net/spree/products/703/product/large_A1374H11_1.png?1623727816",
    price: 49.99 + "€",
},
{
    id: 67,
    name: "Razer BlackWidow Elite Mechanical Keyboard",
    description: "A mechanical gaming keyboard with customizable RGB lighting and dedicated media controls.",
    image: "https://images.razer.com/image/upload/c_pad,f_auto,h_800,q_auto,w_800/v1558971509/rzer/tridentslack/image/product-new/hero/aHR0cDovL3d3dy5yYXplci5jb20vMDIwODAwMDcvMDMvMDc1Mzk2MzgvMDIxODExLTA1OTE5N18xMjU3MzU5Ml9jb3B5LTIwMDB4MjAwLmpwZz82NTI5ODcwODI4NDI3",
    price: 159.99 + "€",
},
{
    id: 68,
    name: "Epson EcoTank ET-2760 Wireless Printer",
    description: "A wireless printer with refillable ink tanks for cost-effective and high-quality printing.",
    image: "https://www.epson.eu/dcd/products/07/26/36/56/EPT_X45XX_Front_Final4_257x257-500x500.png",
    price: 349.99 + "€",
},
{
    id: 69,
    name: "Xbox Series X Gaming Console",
    description: "The next-gen Xbox console for powerful gaming performance and a vast library of games.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71eVFL9u3nL._SL1500_.jpg",
    price: 499.99 + "€",
},
{
    id: 70,
    name: "Nest Learning Thermostat",
    description: "A smart thermostat that learns your preferences and optimizes your home's energy usage.",
    image: "https://images.ctfassets.net/81o3ofbt65a1/6ZdLbn6Hwn5lVpDBy75RC4/3831012e5bfb1952e527a5408cbf28d8/nestlearningthermostat_gallery.jpg?w=280&h=300",
    price: 219.99 + "€",
},
{
    id: 71,
    name: "ASUS ROG Strix G15 Gaming Laptop",
    description: "A high-performance gaming laptop with a fast refresh rate display and powerful GPU.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71bNrJdolVL._AC_SL1500_.jpg",
    price: 1499.99 + "€",
},
{
    id: 72,
    name: "Nikon Z6 Mirrorless Camera",
    description: "A versatile mirrorless camera with 4K video capabilities and advanced photography features.",
    image: "https://cdn-5.nikon-cdn.com/assets/img/shared/dslr/z_6/img/product-overview/gallery/z_6_01_03.jpg",
    price: 1799.99 + "€",
},
{
    id: 73,
    name: "Bowers & Wilkins PX7 Wireless Headphones",
    description: "Premium wireless headphones with adaptive noise canceling and high-quality audio.",
    image: "https://images.bowerswilkins.com/launch/px/series-1/gallery/px7-carbon-rgb-1-800x800.jpg",
    price: 399.99 + "€",
},
{
    id: 74,
    name: "Canon PIXMA Pro-100 Wireless Printer",
    description: "A professional photo printer for producing high-quality prints with exceptional color accuracy.",
    image: "https://www.usa.canon.com/internet/wcm/connect/us/a801a2ed-c86d-45e2-9881-0443db270f2e/canon-pixma-pro-100-front-view-0319-15996b.jpg?MOD=AJPERES&CACHEID=ROOTWORKSPACE.Z18-M9G9KI80AOC2A90M7ED8I01-2-a801a2ed-c86d-45e2-9881-0443db270f2e-nQmwvem",
    price: 349.99 + "€",
},
{
    id: 75,
    name: "Microsoft Surface Laptop 4",
    description: "A sleek and powerful laptop with a high-resolution PixelSense touchscreen display.",
    image: "https://images.pcmac.com/wp-content/uploads/2021/04/Microsoft-Surface-Laptop-4-2.jpg",
    price: 1199.99 + "€",
},
{
    id: 76,
    name: "LG CX 4K OLED TV",
    description: "A 4K OLED TV with deep blacks and stunning colors for an immersive viewing experience.",
    image: "https://images.lg.com/us/largeTv/md07508490/gallery/desktop-01.jpg",
    price: 2499.99 + "€",
},
{
    id: 77,
    name: "Sonos Beam Soundbar",
    description: "A compact soundbar for enhancing your home theater audio with voice control and streaming capabilities.",
    image: "https://m.media-amazon.com/images/I/71vtLL9Ce3L._AC_SL1500_.jpg",
    price: 399.99 + "€",
},
{
    id: 78,
    name: "OnePlus 9 Pro 5G Smartphone",
    description: "A 5G smartphone with a high-refresh-rate display and a versatile camera system.",
    image: "https://cdn-files.kimovil.com/2021/04/07/583/1b8452f3b1b16e3ad369ce6f4a94dd4e.jpg",
    price: 699.99 + "€",
},
{
    id: 79,
    name: "Sony A7 III Mirrorless Camera",
    description: "A full-frame mirrorless camera with advanced features for both photography and videography.",
    image: "https://images.sony.com/is/image/Sony/SEL2470GM_FRONT-features-page-hero?$jpgp$&fmt=jpg&wid=330&hei=330&bgcolor=FFFFFF",
    price: 1999.99 + "€",
},
{
    id: 80,
    name: "GoPro HERO9 Black",
    description: "The HERO9 Black action camera with 5K video recording and advanced stabilization.",
    image: "https://images-na.ssl-images-amazon.com/images/I/61lKkq0JUCL._AC_SL1500_.jpg",
    price: 549.99 + "€",
},
{
    id: 81,
    name: "Apple AirPods Max",
    description: "High-fidelity over-ear headphones with spatial audio and active noise canceling.",
    image: "https://m.media-amazon.com/images/I/81on8XbpZHL._AC_SL1500_.jpg",
    price: 549.99 + "€",
},
{
    id: 82,
    name: "Lenovo ThinkPad X1 Carbon",
    description: "An ultra-light and durable business laptop with a high-resolution display and powerful performance.",
    image: "https://i.dell.com/is/image/DellContent//content/dam/global-site-design/product_images/notebooks/xps_13_9310/visuals/ng/notebooks-xps-13-9310-visual-front.png?fmt=webp",
    price: 1699.99 + "€",
},
{
    id: 83,
    name: "Fitbit Charge 5 Fitness Tracker",
    description: "A fitness tracker with built-in GPS and health insights for an active lifestyle.",
    image: "https://m.media-amazon.com/images/I/81dDFl-cVTL._AC_SL1500_.jpg",
    price: 129.99 + "€",
},
{
    id: 84,
    name: "Dell Alienware Aurora Gaming Desktop",
    description: "A high-performance gaming desktop with customizable lighting and powerful components.",
    image: "https://i.dell.com/is/image/DellContent//content/dam/global-site-design/product_images/inspiron_24_5400_aio/visuals/spi/inspiron-24-5400-visual-right-laying.png?fmt=webp",
    price: 2199.99 + "€",
},
{
    id: 85,
    name: "Epson EcoTank ET-3760 Wireless Printer",
    description: "A wireless printer with refillable ink tanks for cost-effective and high-quality printing.",
    image: "https://www.epson.eu/dcd/products/07/63/39/56/EPT_X45XX_Front_Final5_257x257-500x500.png",
    price: 449.99 + "€",
},
{
    id: 86,
    name: "Bose QuietComfort 45 Wireless Headphones",
    description: "Wireless noise-canceling headphones with premium audio and long-lasting comfort.",
    image: "https://images-na.ssl-images-amazon.com/images/I/61hZpJfN9PL._AC_SL1200_.jpg",
    price: 349.99 + "€",
},
{
    id: 87,
    name: "Xiaomi Mi Electric Scooter Pro 2",
    description: "An electric scooter with a long-range battery and foldable design for easy transportation.",
    image: "https://images-na.ssl-images-amazon.com/images/I/81L0YMSO8ZL._AC_SL1500_.jpg",
    price: 599.99 + "€",
},
{
    id: 88,
    name: "Google Nest Hub (2nd Gen)",
    description: "A smart display with Google Assistant for controlling your smart home and accessing information.",
    image: "https://m.media-amazon.com/images/I/71x4Vpx8GwL._AC_SL1500_.jpg",
    price: 99.99 + "€",
},
{
    id: 89,
    name: "Roku Ultra Streaming Player",
    description: "A 4K streaming player with enhanced remote for accessing a wide range of streaming services.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71PCuXTX+EL._AC_SL1500_.jpg",
    price: 89.99 + "€",
},
{
    id: 90,
    name: "HP Envy 27-inch 4K Monitor",
    description: "A 4K monitor with a slim design and vibrant colors for professional and entertainment use.",
    image: "https://images.hp.com/is/image/HPInc/LB_09_Art_Standard__090__0004?$jpg$&wid=499&hei=631",
    price: 499.99 + "€",
},
{
    id: 91,
    name: "Anker SoundCore Mini Portable Speaker",
    description: "A compact and portable Bluetooth speaker with impressive audio quality.",
    image: "https://m.media-amazon.com/images/I/61Cfo6e-baL._AC_SL1500_.jpg",
    price: 29.99 + "€",
},
{
    id: 92,
    name: "Samsung Galaxy Watch 4",
    description: "A smartwatch with fitness tracking and health monitoring features.",
    image: "https://m.media-amazon.com/images/I/71fv3BCVJmS._AC_SL1500_.jpg",
    price: 249.99 + "€",
},
{
    id: 93,
    name: "DJI Air 2S Drone",
    description: "A compact drone with a high-resolution camera and intelligent flight features.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71tG7QzCRvL._AC_SL1500_.jpg",
    price: 999.99 + "€",
},
{
    id: 94,
    name: "Logitech C920 HD Pro Webcam",
    description: "A high-definition webcam for video conferencing and streaming.",
    image: "https://m.media-amazon.com/images/I/61UnN5-HGSL._AC_SL1500_.jpg",
    price: 79.99 + "€",
},
{
    id: 95,
    name: "Ultimate Ears BOOM 3 Portable Speaker",
    description: "A portable Bluetooth speaker with 360-degree sound and water resistance.",
    image: "https://images-na.ssl-images-amazon.com/images/I/61gPGtozTyL._AC_SL1500_.jpg",
    price: 129.99 + "€",
},
{
    id: 96,
    name: "Corsair K95 RGB Platinum XT Mechanical Keyboard",
    description: "A premium mechanical gaming keyboard with customizable RGB lighting and macro keys.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71o%2BX8zIe2L._AC_SL1500_.jpg",
    price: 169.99 + "€",
},
{
    id: 97,
    name: "Nest Cam Indoor Security Camera",
    description: "An indoor security camera for monitoring your home with 24/7 live video and alerts.",
    image: "https://m.media-amazon.com/images/I/81UEebcbTmL._AC_SL1500_.jpg",
    price: 199.99 + "€",
},
{
    id: 98,
    name: "Xbox Wireless Controller",
    description: "A wireless controller for Xbox gaming with textured grips and custom button mapping.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71vsoSsAj3L._AC_SL1500_.jpg",
    price: 59.99 + "€",
},
{
    id: 99,
    name: "Lenovo Legion Y27gq-20 Gaming Monitor",
    description: "A high-refresh-rate gaming monitor with NVIDIA G-SYNC for smooth and immersive gameplay.",
    image: "https://images.lenovo.com/medias/legion-y27gq-20-feature-02.png?context=bWFzdGVyfHJvb3R8NjAzNzB8aW1hZ2UvcG5nfGg4Yi9oNjUvOTY3MjIwNzA4ODI5MzgucG5nfDU0YzJlY2MwODA5NjI0MTk2NGJiMzQwOWE0NmZiNTA3MDlmZGEyYzEzNzAzZDgxMzZhNDViY2MzOWZmMTJiMTI",
    price: 549.99 + "€",
},
{
    id: 100,
    name: "Canon EF 70-200mm f/2.8L IS III USM Lens",
    description: "A professional telephoto lens for Canon DSLR cameras with advanced optics and image stabilization.",
    image: "https://m.media-amazon.com/images/I/81s46iKUB8L._AC_SL1500_.jpg",
    price: 2199.99 + "€",
},
{
    id: 101,
    name: "Sony PlayStation 5",
    description: "The next-gen gaming console for immersive gaming experiences and 4K gaming.",
    image: "https://images-na.ssl-images-amazon.com/images/I/619BkvKW35L._AC_SX679_.jpg",
    price: 499.99 + "€",
},
{
    id: 102,
    name: "Apple iPad Pro (12.9-inch)",
    description: "A high-performance iPad with a large display, Apple Pencil support, and powerful performance.",
    image: "https://m.media-amazon.com/images/I/71A9Vo1BatL._AC_SX679_.jpg",
    price: 999.99 + "€",
},
{
    id: 103,
    name: "Nikon D850 DSLR Camera",
    description: "A full-frame DSLR camera with high-resolution imaging and advanced photography features.",
    image: "https://m.media-amazon.com/images/I/91rI9RJ5YKL._AC_SX679_.jpg",
    price: 2799.99 + "€",
},
{
    id: 104,
    name: "Sennheiser HD 660 S Open-Back Headphones",
    description: "High-end open-back headphones with exceptional sound quality and comfort for audiophiles.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71-jW0Sj1-L._AC_SX679_.jpg",
    price: 499.99 + "€",
},
{
    id: 105,
    name: "Canon EOS R6 Mirrorless Camera",
    description: "A versatile mirrorless camera with 4K video capabilities and advanced photography features.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71WUTKrlp7L._AC_SX679_.jpg",
    price: 2499.99 + "€",
},
{
    id: 106,
    name: "Bose QuietComfort 35 II Wireless Headphones",
    description: "Wireless noise-canceling headphones with balanced audio and long-lasting comfort.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71zofqI5FvL._AC_SX679_.jpg",
    price: 299.99 + "€",
},
{
    id: 107,
    name: "Samsung 32-Inch 4K Monitor",
    description: "A 4K monitor with vibrant colors and a large screen for work and entertainment.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71mj5Wd5gML._AC_SX679_.jpg",
    price: 399.99 + "€",
},
{
    id: 108,
    name: "Dell XPS 15 Laptop",
    description: "A premium laptop with a 4K InfinityEdge display and powerful performance for professionals.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71gjJMPaQaL._AC_SX679_.jpg",
    price: 1499.99 + "€",
},
{
    id: 109,
    name: "Fitbit Versa 3 Smartwatch",
    description: "A smartwatch with fitness tracking, GPS, and health insights for an active lifestyle.",
    image: "https://m.media-amazon.com/images/I/71ApNxohFjS._AC_SX679_.jpg",
    price: 229.99 + "€",
},
{
    id: 110,
    name: "Anker PowerCore 26800 Portable Charger",
    description: "A high-capacity portable charger with fast charging for smartphones and tablets.",
    image: "https://m.media-amazon.com/images/I/71ZszEp6uUL._AC_SX679_.jpg",
    price: 59.99 + "€",
},
{
    id: 111,
    name: "Razer Naga X Gaming Mouse",
    description: "A lightweight and customizable gaming mouse for competitive gaming.",
    image: "https://images-na.ssl-images-amazon.com/images/I/81FfWOUKrTL._AC_SX679_.jpg",
    price: 59.99 + "€",
},
{
    id: 112,
    name: "LG CX 48-Inch 4K OLED TV",
    description: "A 4K OLED TV with deep blacks and stunning colors for an immersive viewing experience.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71jFnvdQT7L._AC_SX679_.jpg",
    price: 2199.99 + "€",
},
{
    id: 113,
    name: "JBL Charge 5 Portable Speaker",
    description: "A portable Bluetooth speaker with high-quality sound and long battery life.",
    image: "https://images-na.ssl-images-amazon.com/images/I/81M3rGP3H5L._AC_SX679_.jpg",
    price: 179.99 + "€",
},
{
    id: 114,
    name: "TP-Link Deco Mesh WiFi System",
    description: "A mesh WiFi system for whole-home coverage and fast internet speeds.",
    image: "https://images-na.ssl-images-amazon.com/images/I/61XJwCWwd8L._AC_SX679_.jpg",
    price: 199.99 + "€",
},
{
    id: 115,
    name: "Satechi Aluminum Bluetooth Keyboard",
    description: "A sleek Bluetooth keyboard for typing and productivity across multiple devices.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71t8lwZtVeL._AC_SX679_.jpg",
    price: 79.99 + "€",
},
{
    id: 116,
    name: "Garmin Forerunner 945 GPS Watch",
    description: "A GPS watch with advanced running dynamics and performance monitoring.",
    image: "https://images-na.ssl-images-amazon.com/images/I/81Zw2RtqvfL._AC_SX679_.jpg",
    price: 499.99 + "€",
},
{
    id: 117,
    name: "Corsair Void RGB Elite Wireless Gaming Headset",
    description: "A wireless gaming headset with 7.1 surround sound and customizable RGB lighting.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71Mf29I%2B8FL._AC_SX679_.jpg",
    price: 99.99 + "€",
},
{
    id: 118,
    name: "SanDisk Extreme Portable SSD (2TB)",
    description: "A high-speed portable SSD with 2TB of storage for fast data transfer and backup.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71u7aon28yL._AC_SX679_.jpg",
    price: 349.99 + "€",
},
{
    id: 119,
    name: "Apple Magic Mouse 2",
    description: "A sleek and rechargeable mouse for seamless navigation and gesture controls.",
    image: "https://images-na.ssl-images-amazon.com/images/I/61BrC%2BU8L9L._AC_SX679_.jpg",
    price: 79.99 + "€",
},
{
    id: 120,
    name: "Canon PIXMA Pro-100 Wireless Color Printer",
    description: "A professional color printer for photo printing and high-quality document output.",
    image: "https://images-na.ssl-images-amazon.com/images/I/81ZelLczATL._AC_SX679_.jpg",
    price: 299.99 + "€",
},
{
    id: 121,
    name: "Seagate Backup Plus Portable 5TB External Hard Drive",
    description: "A high-capacity external hard drive for backing up and storing your data.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71sqb9rWj9L._AC_SX679_.jpg",
    price: 129.99 + "€",
},
{
    id: 122,
    name: "Amazon Echo Dot (4th Gen)",
    description: "A smart speaker with Alexa for voice control and smart home integration.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71gN75yWddL._AC_SX679_.jpg",
    price: 49.99 + "€",
},
{
    id: 123,
    name: "Acer Predator Helios 300 Gaming Laptop",
    description: "A gaming laptop with a high-refresh-rate display and powerful graphics for gaming performance.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71K7c%2BbkoFL._AC_SX679_.jpg",
    price: 1199.99 + "€",
},
{
    id: 124,
    name: "Logitech MX Master 3 Wireless Mouse",
    description: "A versatile wireless mouse with customizable buttons and ergonomic design.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71hxX9OrV2L._AC_SX679_.jpg",
    price: 99.99 + "€",
},
{
    id: 125,
    name: "Sony WH-1000XM4 Wireless Noise-Canceling Headphones",
    description: "Premium wireless headphones with industry-leading noise cancellation and hi-res audio.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71EIDJkHw7L._AC_SX679_.jpg",
    price: 349.99 + "€",
},
{
    id: 126,
    name: "Asus ROG Strix Scar 17 Gaming Laptop",
    description: "A high-performance gaming laptop with a 17-inch display and RTX 30 series graphics.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71mNUAnbEXL._AC_SX679_.jpg",
    price: 2499.99 + "€",
},
{
    id: 127,
    name: "Ring Video Doorbell 3",
    description: "A video doorbell with enhanced motion detection and 1080p HD video for home security.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71KZpCk4DDL._AC_SX679_.jpg",
    price: 199.99 + "€",
},
{
    id: 128,
    name: "Bose SoundLink Revolve+ Portable Speaker",
    description: "A portable Bluetooth speaker with 360-degree sound and long-lasting battery life.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71TzTvwz3xL._AC_SX679_.jpg",
    price: 299.99 + "€",
},
{
    id: 129,
    name: "SteelSeries Apex Pro Mechanical Gaming Keyboard",
    description: "A customizable mechanical gaming keyboard with adjustable actuation switches.",
    image: "https://images-na.ssl-images-amazon.com/images/I/61U3l2bRKwL._AC_SX679_.jpg",
    price: 199.99 + "€",
},
{
    id: 130,
    name: "LG OLED C1 55-Inch 4K TV",
    description: "A 4K OLED TV with stunning picture quality and smart TV features.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71z-WQFQhXL._AC_SX679_.jpg",
    price: 1799.99 + "€",
},
{
    id: 131,
    name: "Razer BlackWidow V3 Pro Wireless Mechanical Keyboard",
    description: "A wireless mechanical gaming keyboard with Razer Chroma RGB and customizable switches.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71HTiIHbN3L._AC_SX679_.jpg",
    price: 229.99 + "€",
},
{
    id: 132,
    name: "LG 34-Inch Ultrawide QHD Monitor",
    description: "An ultrawide QHD monitor for multitasking and immersive gaming.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71dVdZJxUPL._AC_SX679_.jpg",
    price: 449.99 + "€",
},
{
    id: 133,
    name: "TP-Link Archer C4000 Tri-Band WiFi Router",
    description: "A tri-band WiFi router for high-performance and reliable network connectivity.",
    image: "https://images-na.ssl-images-amazon.com/images/I/61Gc7g8JQdL._AC_SX679_.jpg",
    price: 149.99 + "€",
},
{
    id: 134,
    name: "Fitbit Sense Advanced Health Smartwatch",
    description: "A health-focused smartwatch with EDA and ECG sensors for holistic well-being.",
    image: "https://images-na.ssl-images-amazon.com/images/I/81XnhU1F9TL._AC_SX679_.jpg",
    price: 299.99 + "€",
},
{
    id: 135,
    name: "Acer Predator X34P 34-Inch Ultrawide Gaming Monitor",
    description: "An ultrawide gaming monitor with G-Sync and high refresh rates for immersive gaming.",
    image: "https://images-na.ssl-images-amazon.com/images/I/81t%2B2yCTx0L._AC_SX679_.jpg",
    price: 799.99 + "€",
},
{
    id: 136,
    name: "DJI Mavic Air 2 Drone",
    description: "A compact drone with 4K video and intelligent flight modes for aerial photography.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71KgU3Q0ZmL._AC_SX679_.jpg",
    price: 799.99 + "€",
},
{
    id: 137,
    name: "Sony Alpha a7 III Mirrorless Camera",
    description: "A full-frame mirrorless camera with 4K video and fast autofocus for professionals.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71nwsjRWtJL._AC_SX679_.jpg",
    price: 1999.99 + "€",
},
{
    id: 138,
    name: "Bowers & Wilkins PX7 Wireless Headphones",
    description: "High-quality wireless headphones with adaptive noise cancellation and premium sound.",
    image: "https://images-na.ssl-images-amazon.com/images/I/61XsYdnkZmL._AC_SX679_.jpg",
    price: 399.99 + "€",
},
{
    id: 139,
    name: "Dell Alienware Aurora R10 Gaming Desktop",
    description: "A high-performance gaming desktop with powerful AMD Ryzen processors and NVIDIA graphics.",
    image: "https://images-na.ssl-images-amazon.com/images/I/61-ty8WXVUL._AC_SX679_.jpg",
    price: 1499.99 + "€",
},
{
    id: 140,
    name: "Apple AirPods Pro",
    description: "Premium wireless earbuds with active noise cancellation and immersive sound.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71z2JS9dsVL._AC_SX679_.jpg",
    price: 249.99 + "€",
},
{
    id: 141,
    name: "Google Pixelbook Go Chromebook",
    description: "A lightweight Chromebook with a stunning touchscreen display and long battery life.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71bJqfbeyCL._AC_SX679_.jpg",
    price: 649.99 + "€",
},
{
    id: 142,
    name: "NVIDIA GeForce RTX 3080 Graphics Card",
    description: "A high-end graphics card for gaming and content creation with ray tracing capabilities.",
    image: "https://images-na.ssl-images-amazon.com/images/I/81MInIitOML._AC_SX679_.jpg",
    price: 699.99 + "€",
},
{
    id: 143,
    name: "Logitech G Pro X Mechanical Gaming Keyboard",
    description: "A professional mechanical gaming keyboard with swappable switches and RGB lighting.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71vZHDLPLSL._AC_SX679_.jpg",
    price: 129.99 + "€",
},
{
    id: 144,
    name: "Samsung Odyssey G9 49-Inch Ultrawide Gaming Monitor",
    description: "An ultrawide gaming monitor with 240Hz refresh rate and QLED technology for gaming enthusiasts.",
    image: "https://images-na.ssl-images-amazon.com/images/I/61YeL6DCmvL._AC_SX679_.jpg",
    price: 1499.99 + "€",
},
{
    id: 145,
    name: "Nintendo Switch Lite",
    description: "A compact and portable gaming console for on-the-go gaming experiences.",
    image: "https://images-na.ssl-images-amazon.com/images/I/51jW5gXHl0L._AC_SX679_.jpg",
    price: 199.99 + "€",
},
{
    id: 146,
    name: "Microsoft Surface Pro 7",
    description: "A versatile 2-in-1 laptop with touchscreen and Microsoft Surface Pen support.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71TRZAw9XRL._AC_SX679_.jpg",
    price: 799.99 + "€",
},
{
    id: 147,
    name: "Amazon Kindle Paperwhite",
    description: "A waterproof e-reader with a high-resolution display for avid readers.",
    image: "https://images-na.ssl-images-amazon.com/images/I/61UGikOYK1L._AC_SX679_.jpg",
    price: 129.99 + "€",
},
{
    id: 148,
    name: "Logitech G Pro Wireless Gaming Mouse",
    description: "A high-performance wireless gaming mouse with LIGHTSPEED technology and HERO sensor.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71vZhEXAO5L._AC_SX679_.jpg",
    price: 149.99 + "€",
},
{
    id: 149,
    name: "AOC CQ32G1 32-Inch QHD Curved Gaming Monitor",
    description: "A curved gaming monitor with high resolution and AMD FreeSync for immersive gameplay.",
    image: "https://images-na.ssl-images-amazon.com/images/I/711M2AvVV1L._AC_SX679_.jpg",
    price: 349.99 + "€",
},
{
    id: 150,
    name: "Roku Streaming Stick+ 4K Streaming Player",
    description: "A 4K streaming player with a voice remote for streaming your favorite content.",
    image: "https://images-na.ssl-images-amazon.com/images/I/81ozZunE4PL._AC_SX679_.jpg",
    price: 59.99 + "€",
},
{
    id: 151,
    name: "SteelSeries Arctis 7 Wireless Gaming Headset",
    description: "A wireless gaming headset with DTS Headphone:X v2.0 and clear voice communication.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71v6siKsLnL._AC_SX679_.jpg",
    price: 149.99 + "€",
},
{
    id: 152,
    name: "BenQ PD2700U 27-Inch 4K Designer Monitor",
    description: "A 4K designer monitor with accurate color reproduction for creative professionals.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71qoG1WeKFL._AC_SX679_.jpg",
    price: 549.99 + "€",
},
{
    id: 153,
    name: "Jabra Elite 85t Wireless Earbuds",
    description: "Wireless earbuds with advanced noise cancellation and customizable sound profiles.",
    image: "https://images-na.ssl-images-amazon.com/images/I/61i3NnVpVcL._AC_SX679_.jpg",
    price: 229.99 + "€",
},
{
    id: 154,
    name: "Sony X900H 65-Inch 4K TV",
    description: "A 4K TV with X1 4K HDR Processor and Android TV for streaming and gaming.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71i46cYw2%2BL._AC_SX679_.jpg",
    price: 1299.99 + "€",
},
{
    id: 155,
    name: "Anker Soundcore Flare 2 Portable Speaker",
    description: "A portable speaker with 360-degree sound and customizable LED lights for party mode.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71MG0%2Bx%2BK6L._AC_SX679_.jpg",
    price: 79.99 + "€",
},
{
    id: 156,
    name: "Samsung Galaxy Tab S7+ Android Tablet",
    description: "A powerful Android tablet with a stunning Super AMOLED display and S Pen support.",
    image: "https://images-na.ssl-images-amazon.com/images/I/711msvn0q8L._AC_SX679_.jpg",
    price: 849.99 + "€",
},
{
    id: 157,
    name: "AMD Ryzen 9 5950X Processor",
    description: "A high-end desktop processor with 16 cores and 32 threads for gaming and content creation.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71MdyPj6mAL._AC_SX679_.jpg",
    price: 799.99 + "€",
},
{
    id: 158,
    name: "ASUS ROG Swift PG279QZ 27-Inch Gaming Monitor",
    description: "A 27-inch gaming monitor with a fast refresh rate and G-Sync technology for competitive gaming.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71pkM1m6iIL._AC_SX679_.jpg",
    price: 499.99 + "€",
},
{
    id: 159,
    name: "Bose Home Speaker 300",
    description: "A smart speaker with built-in voice assistants and room-filling sound for your home.",
    image: "https://images-na.ssl-images-amazon.com/images/I/61dJIWc9v1L._AC_SX679_.jpg",
    price: 199.99 + "€",
},
{
    id: 160,
    name: "Logitech G Pro X Superlight Wireless Gaming Mouse",
    description: "A superlight wireless gaming mouse with HERO sensor and customizable button layouts.",
    image: "https://images-na.ssl-images-amazon.com/images/I/61sSC7cysbL._AC_SX679_.jpg",
    price: 149.99 + "€",
},
{
    id: 161,
    name: "Dell Ultrasharp U2719DX 27-Inch QHD Monitor",
    description: "A QHD monitor with InfinityEdge design and factory color calibration for professionals.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71H7yMRdR%2BL._AC_SX679_.jpg",
    price: 349.99 + "€",
},
{
    id: 162,
    name: "NVIDIA Shield TV Pro 4K HDR Streaming Media Player",
    description: "A 4K streaming media player with AI upscaling and a built-in Plex server for media enthusiasts.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71pTphbTPcL._AC_SX679_.jpg",
    price: 199.99 + "€",
},
{
    id: 163,
    name: "HyperX Cloud II Gaming Headset",
    description: "A gaming headset with 7.1 surround sound and durable aluminum frame for immersive gaming.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71zWMOBbDmL._AC_SX679_.jpg",
    price: 99.99 + "€",
},
{
    id: 164,
    name: "Roku Ultra 4K HDR Streaming Player",
    description: "A 4K streaming player with enhanced voice remote and USB port for local media playback.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71uFg2Ug9sL._AC_SX679_.jpg",
    price: 79.99 + "€",
},
{
    id: 165,
    name: "Elgato Stream Deck XL",
    description: "A professional streaming controller with customizable keys for content creators.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71wJtyiMzEL._AC_SX679_.jpg",
    price: 249.99 + "€",
},
{
    id: 166,
    name: "Canon EF 24-70mm f/2.8L II USM Lens",
    description: "A professional zoom lens with a bright aperture for Canon DSLR cameras.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71TO%2BzksR9L._AC_SX679_.jpg",
    price: 1499.99 + "€",
},
{
    id: 167,
    name: "Fitbit Inspire 2 Fitness Tracker",
    description: "A fitness tracker with heart rate monitoring and up to 10 days of battery life.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71chqV%2BhbJL._AC_SX679_.jpg",
    price: 99.99 + "€",
},
{
    id: 168,
    name: "ASUS TUF Gaming VG279QM 27-Inch Monitor",
    description: "A high-refresh-rate gaming monitor with ELMB Sync and G-Sync compatibility for smooth gameplay.",
    image: "https://images-na.ssl-images-amazon.com/images/I/81J%2Byzjz-gL._AC_SX679_.jpg",
    price: 399.99 + "€",
},
{
    id: 169,
    name: "Sony SRS-XB43 Portable Bluetooth Speaker",
    description: "A portable Bluetooth speaker with EXTRA BASS and built-in lighting effects for parties.",
    image: "https://images-na.ssl-images-amazon.com/images/I/61UvEA5Un6L._AC_SX679_.jpg",
    price: 169.99 + "€",
},
{
    id: 170,
    name: "Nikon AF-S NIKKOR 50mm f/1.8G Lens",
    description: "A fast prime lens with a wide aperture for Nikon DSLR cameras.",
    image: "https://images-na.ssl-images-amazon.com/images/I/81l77lL9DvL._AC_SX679_.jpg",
    price: 219.99 + "€",
},
{
    id: 171,
    name: "Apple Magic Keyboard for iPad Pro",
    description: "A full-size keyboard with trackpad for iPad Pro productivity and multitasking.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71FWnW52kUL._AC_SX679_.jpg",
    price: 299.99 + "€",
},
{
    id: 172,
    name: "HyperX Alloy FPS Pro Mechanical Gaming Keyboard",
    description: "A compact mechanical gaming keyboard with Cherry MX mechanical key switches.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71GAn4-IBFL._AC_SX679_.jpg",
    price: 69.99 + "€",
},
{
    id: 173,
    name: "Rode NT-USB Mini USB Microphone",
    description: "A compact USB microphone for streaming, podcasting, and voice recording.",
    image: "https://images-na.ssl-images-amazon.com/images/I/61t9d%2B%2B4W0L._AC_SX679_.jpg",
    price: 99.99 + "€",
},
{
    id: 174,
    name: "Logitech G Pro Gaming Headset",
    description: "A lightweight gaming headset with Pro-G drivers and premium comfort for competitive gaming.",
    image: "https://images-na.ssl-images-amazon.com/images/I/61DFX5BcNjL._AC_SX679_.jpg",
    price: 89.99 + "€",
},
{
    id: 175,
    name: "Seagate FireCuda 520 1TB NVMe SSD",
    description: "A high-speed NVMe SSD for gaming and content creation with fast data transfer.",
    image: "https://images-na.ssl-images-amazon.com/images/I/61IyDLW1j-L._AC_SX679_.jpg",
    price: 199.99 + "€",
},
{
    id: 176,
    name: "Corsair Dark Core RGB/SE Wired/Wireless Gaming Mouse",
    description: "A versatile gaming mouse with customizable side grips and customizable RGB lighting.",
    image: "https://images-na.ssl-images-amazon.com/images/I/61Pam2zTBdL._AC_SX679_.jpg",
    price: 89.99 + "€",
},
{
    id: 177,
    name: "Apple Smart Keyboard Folio for iPad Air (4th Generation)",
    description: "A slim keyboard folio for iPad Air (4th Gen) with a responsive typing experience.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71mWaj9kA-L._AC_SX679_.jpg",
    price: 179.99 + "€",
},
{
    id: 178,
    name: "JBL PartyBox 300 High Power Portable Wireless Bluetooth Audio System",
    description: "A high-power portable Bluetooth audio system with light shows for epic parties.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71Z2tU2-T4L._AC_SX679_.jpg",
    price: 499.99 + "€",
},
{
    id: 179,
    name: "Epson EcoTank ET-3760 Wireless Color All-in-One Cartridge-Free Supertank Printer",
    description: "A cartridge-free color printer with easy-to-fill ink tanks for printing without replacement cartridges.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71R99wRgSPL._AC_SX679_.jpg",
    price: 399.99 + "€",
},
{
    id: 180,
    name: "Samsung Odyssey G7 27-Inch QHD Curved Gaming Monitor",
    description: "A curved gaming monitor with QLED technology and high refresh rates for competitive gaming.",
    image: "https://images-na.ssl-images-amazon.com/images/I/61-W3xxf5EL._AC_SX679_.jpg",
    price: 599.99 + "€",
},
{
    id: 181,
    name: "Canon EF 70-200mm f/2.8L IS III USM Lens",
    description: "A professional telephoto zoom lens with image stabilization for Canon DSLR cameras.",
    image: "https://images-na.ssl-images-amazon.com/images/I/81OiN4y0qML._AC_SX679_.jpg",
    price: 2099.99 + "€",
},
{
    id: 182,
    name: "Razer BlackShark V2 Pro Wireless Gaming Headset",
    description: "A wireless gaming headset with THX Spatial Audio and advanced noise cancellation.",
    image: "https://images-na.ssl-images-amazon.com/images/I/61GTR4f3f2L._AC_SX679_.jpg",
    price: 179.99 + "€",
},
{
    id: 183,
    name: "ASUS ROG Strix B450-F Gaming II ATX Gaming Motherboard",
    description: "A gaming motherboard with support for AMD Ryzen processors and Aura Sync RGB lighting.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71C6GL6f0tL._AC_SX679_.jpg",
    price: 129.99 + "€",
},
{
    id: 184,
    name: "Sony SRS-XB41 Portable Bluetooth Speaker",
    description: "A portable Bluetooth speaker with EXTRA BASS and LED lights for music and light shows.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71ctyM2sBmL._AC_SX679_.jpg",
    price: 129.99 + "€",
},
{
    id: 185,
    name: "SteelSeries Rival 600 Gaming Mouse",
    description: "A dual-sensor gaming mouse with customizable weight and split-trigger buttons.",
    image: "https://images-na.ssl-images-amazon.com/images/I/81a3PLbMFlL._AC_SX679_.jpg",
    price: 79.99 + "€",
},
{
    id: 186,
    name: "TP-Link Archer AX11000 Tri-Band Gaming Router",
    description: "A tri-band gaming router with 802.11ax Wi-Fi and advanced security features for online gaming.",
    image: "https://images-na.ssl-images-amazon.com/images/I/61uK5wBiR1L._AC_SX679_.jpg",
    price: 399.99 + "€",
},
{
    id: 187,
    name: "Garmin Forerunner 945 GPS Running Watch",
    description: "A GPS running watch with advanced training features and music streaming support.",
    image: "https://images-na.ssl-images-amazon.com/images/I/81p8GQR9eSL._AC_SX679_.jpg",
    price: 499.99 + "€",
},
{
    id: 188,
    name: "Dell P2719H 27-Inch Monitor",
    description: "A 27-inch monitor with in-plane switching and flicker-free screen for eye comfort.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71vw%2B%2BqoEiL._AC_SX679_.jpg",
    price: 229.99 + "€",
},
{
    id: 189,
    name: "Xbox Wireless Controller - Shock Blue",
    description: "A wireless controller with textured grip and custom button mapping for Xbox gaming.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71a7OsibndL._AC_SX679_.jpg",
    price: 64.99 + "€",
},
{
    id: 190,
    name: "Western Digital Black 6TB Performance Internal Hard Drive",
    description: "A high-performance internal hard drive with dual processors and dynamic caching for gaming and creative applications.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71cAvj6z6SL._AC_SX679_.jpg",
    price: 229.99 + "€",
},
{
    id: 191,
    name: "LG 27UL850-W 27-Inch 4K UHD IPS Monitor with USB Type-C",
    description: "A 4K UHD monitor with USB Type-C connectivity and HDR for content creators and professionals.",
    image: "https://images-na.ssl-images-amazon.com/images/I/81Tibq9lYeL._AC_SX679_.jpg",
    price: 499.99 + "€",
},
{
    id: 192,
    name: "Logitech G433 7.1 Wired Gaming Headset",
    description: "A wired gaming headset with DTS Headphone:X technology and a lightweight, hydrophobic fabric shell.",
    image: "https://images-na.ssl-images-amazon.com/images/I/61XzUVzBvaL._AC_SX679_.jpg",
    price: 79.99 + "€",
},
{
    id: 193,
    name: "Sony WH-CH700N Wireless Noise-Canceling Headphones",
    description: "Wireless headphones with noise-canceling technology and long battery life for a distraction-free listening experience.",
    image: "https://images-na.ssl-images-amazon.com/images/I/61bD4s2z8SL._AC_SX679_.jpg",
    price: 149.99 + "€",
},
{
    id: 194,
    name: "Corsair K70 RGB MK.2 Mechanical Gaming Keyboard",
    description: "A mechanical gaming keyboard with per-key RGB backlighting and dedicated media controls.",
    image: "https://images-na.ssl-images-amazon.com/images/I/61Xe3mKvz8L._AC_SX679_.jpg",
    price: 159.99 + "€",
},
{
    id: 195,
    name: "ASUS ROG Swift PG27UQ 27-Inch 4K UHD Gaming Monitor",
    description: "A 4K UHD gaming monitor with G-Sync HDR and quantum-dot technology for stunning visuals.",
    image: "https://images-na.ssl-images-amazon.com/images/I/81K8nd06V4L._AC_SX679_.jpg",
    price: 1999.99 + "€",
},
{
    id: 196,
    name: "SanDisk Extreme Pro 1TB Portable SSD",
    description: "A high-speed portable SSD with rugged design and up to 1050MB/s read and write speeds.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71khRm1d09L._AC_SX679_.jpg",
    price: 249.99 + "€",
},
{
    id: 197,
    name: "Elgato Game Capture 4K60 Pro MK.2 - 4K 60fps Capture Card",
    description: "A 4K capture card with ultra-low latency and Instant Gameview for professional game streaming.",
    image: "https://images-na.ssl-images-amazon.com/images/I/71nMAo5hPL%2BL._AC_SX679_.jpg",
    price: 249.99 + "€",
},
{
    id: 198,
    name: "Google Nest Hub Max Smart Display",
    description: "A smart display with Google Assistant and a 10-inch HD screen for smart home control and video calls.",
    image: "https://images-na.ssl-images-amazon.com/images/I/61qPEek2RML._AC_SX679_.jpg",
    price: 229.99 + "€",
},
{
    id: 199,
    name: "NVIDIA GeForce RTX 3090 Founders Edition Graphics Card",
    description: "A high-end graphics card with 24GB of GDDR6X memory and real-time ray tracing for gaming and content creation.",
    image: "https://images-na.ssl-images-amazon.com/images/I/81%2B%2BoKFcGTL._AC_SX679_.jpg",
    price: 1499.99 + "€",
},
];



export function composeProduct(products, limit = null) {
  let html = '';

  const data = (limit == null) ? products : products.slice(0, limit);

  for (let product of data) {
    html += `
      <div class="card p-2 g-col-6  prr" style="width: 19rem;">
        <img src="${product.image}" class="card-img-top">
        
        <div class="card-body">  
          <h5 class="card-title">${product.name}</h5>
          <hr>
          <p>${product.description}</p>
          
          <a href="#" class="btn btn-outline-light">${product.price}</a>
          <a href="#" class="btn btn-outline-light" onclick="addToCart('${product.name}', ${product.price})">
            <i class="fa-solid fa-shopping-cart"></i> Add to Cart
          </a>
          <hr>
          
          <a href="orderpage.html" class="btn btn-outline-light" style="width: 100%;">Order</a>
        </div>
      </div>
    `;
  }
  return html;


}

